<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="BrandUp.Website" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\BrandUp.Pages.Core\BrandUp.Pages.Core.csproj" />
	</ItemGroup>

</Project>
